# -*- coding: utf-8 -*-
"""КамАЗ-5490 по-английски: те же 311 кодов, что в kamaz5490.py.

Переводим не источник, а уже вычищенные русские формулировки — таблицей, как
у старых 119 строк: «Node: fault. K-line code on KamAZ-5490: ADM3 NNNNN.»

    python scripts/kamaz5490_en.py          # показать
    python scripts/kamaz5490_en.py записать # дописать в assets/dtc.en.js
"""
import base64, io, json, os, re, sys

import kamaz5490 as K

NODE = {
    'Автоматическая проверка компрессии': 'Automatic compression test',
    'Аналоговое напряжение питания': 'Analog supply voltage',
    'Блок управления двигателем PLD/MR2': 'Engine control unit PLD/MR2',
    'Блокировка гидротрансформатора коробки': 'Transmission torque converter lock-up',
    'Включение моторного тормоза': 'Engine brake selection',
    'Включение ретардера (не моторного тормоза)': 'Retarder selection (non-engine)',
    'Выбранная передача коробки': 'Selected transmission gear',
    'Выброс NOx': 'NOx emissions',
    'Выключатель двухступенчатого моста': 'Two-speed axle switch',
    'Выключатель кикдауна педали газа': 'Accelerator pedal kickdown switch',
    'Выключатель круиз-контроля «CC+» (возобновить, установить)': 'Cruise control switch CC+ (resume, set)',
    'Выключатель круиз-контроля «CC−» (установить, ограничить)': 'Cruise control switch CC− (set, limit)',
    'Выключатель круиз-контроля «прибавить»': 'Cruise control accelerate switch',
    'Выключатель ограничителя скорости «убавить»': 'Speed limiter decrease switch',
    'Выключатель паузы круиз-контроля': 'Cruise control pause switch',
    'Выключатель стояночного тормоза': 'Parking brake switch',
    'Выключатель холостого хода педали газа (GAS1, GAS2 или по J1939)': 'Accelerator pedal idle switch (GAS1, GAS2 or J1939)',
    'Выходное реле 2 (REL 2)': 'Output relay 2 (REL 2)',
    'Выходное реле 4 (REL 4)': 'Output relay 4 (REL 4)',
    'Давление в ресивере системы SCR': 'SCR system air reservoir pressure',
    'Давление в системе мочевины (AdBlue)': 'AdBlue system pressure',
    'Давление топлива': 'Fuel pressure',
    'Давление топлива на входе топливного клапана 1': 'Fuel pressure at fuel valve 1 inlet',
    'Датчик NOx': 'NOx sensor',
    'Датчик атмосферного давления в блоке PLD/MR2': 'Barometric pressure sensor in PLD/MR2',
    'Датчик атмосферного давления впрыска мочевины (AdBlue)': 'AdBlue dosing barometric pressure sensor',
    'Датчик давления мочевины (AdBlue)': 'AdBlue pressure sensor',
    'Датчик давления перед сажевым фильтром': 'DPF inlet pressure sensor',
    'Датчик давления после сажевого фильтра': 'DPF outlet pressure sensor',
    'Датчик засорённости воздушного фильтра': 'Air filter restriction sensor',
    'Датчик наружного воздуха: влажность': 'Ambient air sensor: humidity',
    'Датчик наружного воздуха: температура': 'Ambient air sensor: temperature',
    'Датчик оборотов турбокомпрессора': 'Turbocharger speed sensor',
    'Датчик положения привода дроссельной заслонки': 'Throttle actuator position sensor',
    'Датчик положения распредвала': 'Camshaft position sensor',
    'Датчик температуры в баке мочевины (AdBlue)': 'AdBlue tank temperature sensor',
    'Датчик температуры воздуха на впуске 2': 'Intake air temperature sensor 2',
    'Датчик температуры катализатора 1': 'Catalyst temperature sensor 1',
    'Датчик температуры катализатора 2': 'Catalyst temperature sensor 2',
    'Датчик температуры мочевины (AdBlue)': 'AdBlue temperature sensor',
    'Датчик температуры перед окислительным катализатором': 'DOC inlet temperature sensor',
    'Датчик температуры после окислительного катализатора': 'DOC outlet temperature sensor',
    'Датчик уровня мочевины (AdBlue)': 'AdBlue level sensor',
    'Датчик уровня мочевины (AdBlue), исполнение Tier 4i': 'AdBlue level sensor (Tier 4i)',
    'Датчики температуры катализатора': 'Catalyst temperature sensors',
    'Дистанционная педаль газа (HFG)': 'Remote accelerator (HFG)',
    'Дозатор мочевины SCR': 'SCR dosing unit',
    'Дозирование мочевины (AdBlue)': 'AdBlue dosing',
    'Дроссельная заслонка на впуске': 'Intake throttle',
    'Дроссельная заслонка на впуске: выходной ключ питания': 'Intake throttle high-side driver',
    'Дроссельная заслонка после турбокомпрессора': 'Intake throttle after turbocharger',
    'Иммобилайзер': 'Immobilizer',
    'Калибровка системы SCR': 'SCR system calibration',
    'Катализатор SCR': 'SCR catalyst',
    'Катушка зажигания цилиндра 1': 'Ignition coil, cylinder 1',
    'Катушка зажигания цилиндра 2': 'Ignition coil, cylinder 2',
    'Катушка зажигания цилиндра 3': 'Ignition coil, cylinder 3',
    'Катушка зажигания цилиндра 4': 'Ignition coil, cylinder 4',
    'Катушка зажигания цилиндра 5': 'Ignition coil, cylinder 5',
    'Катушка зажигания цилиндра 6': 'Ignition coil, cylinder 6',
    'Клапан моторного тормоза (заслонка в выпуске, PLD/MR2)': 'Exhaust brake valve (PLD/MR2)',
    'Клапан отсечки топлива': 'Fuel shutoff valve',
    'Клапан подогрева бака мочевины (AdBlue)': 'AdBlue tank heating valve',
    'Контроль подачи мочевины (AdBlue)': 'AdBlue dosing control',
    'Концентрация NOx в выхлопе': 'Exhaust NOx concentration',
    'Лямбда-зонд 2 на входе нейтрализатора': 'Aftertreatment inlet oxygen sensor 2',
    'Лямбда-зонд: коррекция подачи топлива': 'Oxygen sensor fuel trim',
    'Маслоотделитель картерных газов': 'Crankcase oil separator',
    'Мочевина (AdBlue) для нейтрализации NOx': 'AdBlue (NOx reductant)',
    'Насос мочевины (AdBlue)': 'AdBlue pump',
    'Обороты вентилятора': 'Fan speed',
    'Обороты входного вала коробки передач': 'Transmission input shaft speed',
    'Обороты выходного вала коробки': 'Transmission output shaft speed',
    'Обороты генератора': 'Alternator speed',
    'Опорное напряжение датчиков 5 В, линия 1': '5 V sensor supply 1',
    'Опорное напряжение датчиков 5 В, линия 2': '5 V sensor supply 2',
    'Опорное напряжение датчиков, линия A': 'Sensor reference voltage A',
    'Опорное напряжение датчиков, линия B': 'Sensor reference voltage B',
    'Опорное напряжение датчиков, линия C': 'Sensor reference voltage C',
    'Отсечной клапан воздуха системы SCR': 'SCR air shutoff valve',
    'Педаль газа с ШИМ-сигналом (FFG)': 'PWM accelerator pedal (FFG)',
    'Переключение передачи': 'Gear shift in progress',
    'Перепад давления на сажевом фильтре': 'DPF differential pressure',
    'Питание аналоговой педали газа (контакт AFP+)': 'Analog accelerator pedal supply (AFP+)',
    'Питание педали газа с ШИМ-сигналом или коробки (контакт FP+)': 'PWM pedal or transmission supply (FP+)',
    'Подогрев лямбда-зонда на входе нейтрализатора': 'Aftertreatment inlet oxygen sensor heater',
    'Подогрев трубки мочевины (AdBlue)': 'AdBlue line heater',
    'Подогреватель воздуха на впуске (PLD/MR2)': 'Intake air heater (PLD/MR2)',
    'Подогреватель форсунки мочевины SCR': 'SCR dosing nozzle heater',
    'Положение дроссельной заслонки, датчик 2': 'Throttle position sensor 2',
    'Положение привода дроссельной заслонки': 'Throttle actuator position',
    'Постоянный дроссель (моторный тормоз)': 'Constant throttle (engine brake)',
    'Проверка прокрутки коленвала': 'Engine cranking test',
    'Программа блока PLD/MR2': 'PLD/MR2 software',
    'Пропорциональные клапаны': 'Proportional valves',
    'Пропорциональные клапаны модуля SCR': 'SCR module proportional valves',
    'Пропорциональные клапаны, группа 1': 'Proportional valves, group 1',
    'Пропорциональные клапаны, группа 2': 'Proportional valves, group 2',
    'Пропорциональный клапан 1': 'Proportional valve 1',
    'Пропорциональный клапан 2': 'Proportional valve 2',
    'Пропорциональный клапан 3': 'Proportional valve 3',
    'Пропорциональный клапан 4': 'Proportional valve 4',
    'Пропорциональный клапан 5': 'Proportional valve 5',
    'Пропорциональный клапан 6': 'Proportional valve 6',
    'Работа двигателя на холодную (исполнение Tier 4i)': 'Cold engine operation (Tier 4i)',
    'Рабочая температура сажевого фильтра': 'DPF operating temperature',
    'Распределительный клапан воздуха системы SCR': 'SCR air distribution valve',
    'Регенерация сажевого фильтра': 'DPF regeneration',
    'Рециркуляция выхлопных газов (EGR)': 'Exhaust gas recirculation (EGR)',
    'Сажевый фильтр': 'Diesel particulate filter',
    'Связь по CAN между блоками ADM3 и PLD/MR2': 'CAN link between ADM3 and PLD/MR2',
    'Сдвоенный датчик температуры SCRT A': 'Dual temperature sensor SCRT A',
    'Сдвоенный датчик температуры SCRT B': 'Dual temperature sensor SCRT B',
    'Сигнал управления дроссельной заслонкой на впуске': 'Intake throttle control signal',
    'Сигналы пуска и остановки двигателя': 'Engine start/stop signals',
    'Система SCR': 'SCR system',
    'Система SCR: атмосферное давление': 'SCR system: barometric pressure',
    'Скоростная шина CAN': 'High-speed CAN bus',
    'Скорость по передней оси': 'Front axle speed',
    'Скорость по тахографу': 'Tachograph vehicle speed',
    'Средний расход мочевины (AdBlue)': 'Average AdBlue consumption',
    'Тахограф': 'Tachograph',
    'Текущая передача коробки': 'Current transmission gear',
    'Текущий расход мочевины (AdBlue)': 'Current AdBlue consumption',
    'Температура блока управления двигателем': 'Engine ECU temperature',
    'Температура выхлопных газов': 'Exhaust gas temperature',
    'Температура катализатора SCR': 'SCR catalyst temperature',
    'Температура на выходе турбины': 'Turbine outlet temperature',
    'Температура перед катализатором SCR': 'SCR catalyst inlet temperature',
    'Температура после катализатора SCR': 'SCR catalyst outlet temperature',
    'Узел системы SCRT': 'SCRT system component',
    'Управление насосом охлаждающей жидкости': 'Coolant pump control',
    'Уровень мочевины (AdBlue)': 'AdBlue level',
    'Форсунка мочевины (AdBlue), пропорциональный клапан 7': 'AdBlue injector, proportional valve 7',
    'Форсунки группы 1': 'Injector group 1',
    'Форсунки группы 1: баланс цилиндров': 'Injector group 1: cylinder balance',
    'Форсунки группы 2': 'Injector group 2',
}

FAULT = {
    'вне обученного диапазона': 'outside learned range',
    'внутренняя ошибка блока управления': 'internal control unit error',
    'вход замкнут на массу': 'input shorted to ground',
    'вход замкнут на плюс': 'input shorted to positive',
    'выше номинального значения': 'above nominal value',
    'давление в линии насоса вне нормы': 'pump line pressure out of range',
    'давление вне диапазона': 'pressure out of range',
    'давление вне нормы': 'pressure out of range',
    'давление мочевины слишком низкое': 'AdBlue pressure too low',
    'давление слишком высокое': 'pressure too high',
    'давление слишком низкое': 'pressure too low',
    'давление упало ниже допустимого, система отключилась': 'pressure dropped below limit, system shut down',
    'датчик не выходит на рабочий режим': 'sensor not ready',
    'заданный расход слишком большой': 'commanded flow too high',
    'замкнуты цепи обоих выключателей': 'both switch circuits closed',
    'замыкание': 'short circuit',
    'замыкание на массу': 'short to ground',
    'замыкание на плюс АКБ': 'short to battery voltage',
    'замыкание на плюс или обрыв': 'short to positive or open circuit',
    'значение слишком высокое': 'value too high',
    'значение слишком низкое': 'value too low',
    'иммобилайзер TPC сообщает об ошибке цепи стартера': 'TPC immobilizer reports starter circuit fault',
    'катализатор SCR работает плохо': 'SCR catalyst efficiency low',
    'клапан газового замка (CNG): замыкание на массу': 'CNG lock valve: short to ground',
    'клапан газового замка (CNG): замыкание на плюс АКБ': 'CNG lock valve: short to battery voltage',
    'мочевины подаётся меньше нужного': 'AdBlue underdosing',
    'напряжение вне нормы': 'voltage out of range',
    'напряжение выше 5,2 В': 'voltage above 5.2 V',
    'напряжение слишком высокое': 'voltage too high',
    'напряжение слишком низкое': 'voltage too low',
    'не достигнута нужная температура': 'target temperature not reached',
    'не достигнута рабочая температура': 'operating temperature not reached',
    'не настроен (нет параметров)': 'not configured (no parameters)',
    'не прошла продувка насоса воздухом': 'pump air purge failed',
    'не удалось опорожнить напорную трубку': 'pressure line purge failed',
    'неверное число цилиндров': 'wrong number of cylinders',
    'недопустимая работа на холодном двигателе': 'invalid cold engine operation',
    'неисправен': 'faulty',
    'неисправен узел или его цепь': 'component or its circuit faulty',
    'неисправность датчика': 'sensor fault',
    'неисправность цепи': 'circuit fault',
    'нет ответа за отведённое время': 'timeout',
    'нет питания на контакте FP+': 'no supply voltage at FP+',
    'нет связи с блоком PLD/MR2': 'no communication with PLD/MR2',
    'нет сигнала второго канала (GAS2)': 'no signal on channel 2 (GAS2)',
    'нет сигнала первого канала (GAS1)': 'no signal on channel 1 (GAS1)',
    'оба сигнала одинаковые, а должны различаться': 'both signals equal but must differ',
    'обороты слишком низкие': 'speed too low',
    'обрыв цепи': 'open circuit',
    'обрыв цепи датчика или замыкание на плюс': 'sensor circuit open or shorted to positive',
    'общая ошибка управления системой': 'general system control error',
    'одновременно замкнуты CC− и CC+': 'CC− and CC+ closed at the same time',
    'одновременно нажаты CC+ и CC−': 'CC+ and CC− pressed at the same time',
    'отмена': 'cancel',
    'ошибка давления наддува при разгоне': 'boost pressure error during acceleration',
    'ошибка калибровки': 'calibration error',
    'перебой подачи воздуха': 'air supply interruption',
    'перепад давления слишком большой': 'differential pressure too high',
    'перепутана полярность — поменять провода местами': 'reversed polarity — swap the wires',
    'питание вне нормы на контакте HFG+': 'supply voltage out of range at HFG+',
    'плохая мочевина, мало впрыска или неисправен катализатор SCR': 'poor AdBlue quality, underdosing or SCR catalyst fault',
    'плохое качество или недостаточное дозирование мочевины': 'poor AdBlue quality or underdosing',
    'плохое качество мочевины': 'poor AdBlue quality',
    'по шине CAN пришли неверные данные': 'erroneous data received over CAN',
    'повышенный выброс до очистки': 'high engine-out emissions',
    'подменены данные в блоке управления': 'control unit data tampered',
    'подогреватель слишком долго включён': 'heater on for too long',
    'подогреватель слишком долго выключен': 'heater off for too long',
    'положение вне допустимых пределов': 'position out of limits',
    'положение холостого хода вне обученного диапазона': 'idle position outside learned range',
    'после включения подогревателя температура не растёт': 'no temperature rise after heater activation',
    'превышен второй порог': 'level 2 exceeded',
    'превышен первый порог': 'level 1 exceeded',
    'причина не определена': 'unknown cause',
    'провод CAN B замкнут на плюс': 'CAN B wire shorted to positive',
    'прокрутка двигателя без впрыска топлива': 'engine cranking without fuel injection',
    'пропал сигнал: нет ШИМ по первому каналу': 'signal lost: no PWM on channel 1',
    'пропала связь': 'communication lost',
    'пропало сообщение по шине CAN': 'CAN message lost',
    'прописано больше 8 ключей иммобилайзера': 'more than 8 immobilizer keys programmed',
    'разомкнуты цепи обоих выключателей': 'both switch circuits open',
    'расход слишком большой': 'consumption too high',
    'расход слишком маленький': 'consumption too low',
    'регенерация не проходит до конца': 'incomplete regeneration',
    'сигнал вне диапазона или недостоверен': 'signal out of range or implausible',
    'сигнал выключателя «возобновить» приходит с перебоями': 'resume switch signal intermittent',
    'сигнал выключателя «установить» приходит с перебоями': 'set switch signal intermittent',
    'сигнал выше рабочего диапазона': 'signal above normal range',
    'сигнал недостоверен': 'signal implausible',
    'сигнал недостоверен — проверить проводку подрулевого переключателя': 'signal implausible — check steering column switch wiring',
    'сигнал ниже рабочего диапазона': 'signal below normal range',
    'сигнал приходит с перебоями или его нет': 'signal intermittent or missing',
    'сигнал пропадает': 'signal dropout',
    'система работает не так, как должна': 'system performance fault',
    'слишком большое отклонение регулирования': 'control deviation too high',
    'смещение сигнала недостоверно': 'signal offset implausible',
    'сообщение по шине CAN приходит с перебоями': 'CAN message update rate abnormal',
    'температура вне нормы': 'temperature out of range',
    'температура слишком высокая': 'temperature too high',
    'температура слишком низкая': 'temperature too low',
    'узел не отвечает (не установлен или не опознан)': 'component not detected',
    'уровень низкий': 'level low',
    'уровень слишком низкий': 'level too low',
    'функция отключена': 'function disabled',
    'цепь датчика замкнута на массу': 'sensor circuit shorted to ground',
    'число цилиндров не соответствует двигателю': 'cylinder count does not match engine',
}


if __name__ == '__main__':
    путь = os.path.join(K.ROOT, 'assets', 'dtc.en.js')
    сырой = io.open(путь, encoding='utf-8').read()
    b64 = re.search(r"b64='([^']+)'", сырой).group(1)
    en = json.loads(base64.b64decode(b64).decode('utf-8'))
    # те коды источника, которых нет в английской базе (русские уже записаны)
    _, _, _, db = K.загрузить()
    ру = {к: в for к, в in db['brands']['kamaz'].items()
          if к not in en['brands']['kamaz'] and 'Код по K-line на КамАЗ-5490' in в}
    итог, пропуски = {}, []
    for к, т in ру.items():
        m = re.match(r'^(.*)\. Код по K-line на КамАЗ-5490: (.*)\.$', т)
        тело, номер = m.groups()
        # узел ищем по таблице: в нём самом бывает двоеточие («…: влажность»)
        узел = max((у for у in NODE if тело.startswith(у + ': ')), key=len, default='')
        вид = тело[len(узел) + 2:]
        if узел not in NODE or вид not in FAULT:
            пропуски.append((к, узел, вид))
            continue
        итог[к] = '%s: %s. K-line code on KamAZ-5490: %s.' % (NODE[узел], FAULT[вид], номер)
    print('английских', len(итог), 'без перевода', len(пропуски))
    for п in пропуски:
        print('  НЕТ', п)
    for к in list(итог)[:5]:
        print(' ', к, итог[к])
    if sys.argv[1:] == ['записать'] and not пропуски:
        en['brands']['kamaz'].update({к: в for к, в in итог.items() if к not in en['brands']['kamaz']})
        нов = base64.b64encode(json.dumps(en, ensure_ascii=False, separators=(',', ':')).encode('utf-8')).decode('ascii')
        io.open(путь, 'w', encoding='utf-8', newline='').write(сырой.replace(b64, нов, 1))
        print('записано')
